import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Standalone Studio — linted separately from studio/
    "studio/**",
    // Generated by TypeGen — do not lint
    "sanity.types.ts",
    // Internal Claude skill references — not project code
    ".agents/**",
    "agent/**",
  ]),
]);

export default eslintConfig;
